class Distance_Sensor_Constants:
    # CM
    MAX_READING_DISTANCE = 400

    # CM/s
    SPEED_OF_SOUND = 34300
    HALF_SPEED_OF_SOUND = SPEED_OF_SOUND / 2

    # Values in seconds
    DELAY = 0.01		
    SIGNAL_LENGTH = 0.00001
    TIMEOUT = MAX_READING_DISTANCE / HALF_SPEED_OF_SOUND


class Sensing_System_Constants:
    FRONT_SENSOR_TRIG_PIN = 24
    FRONT_SENSOR_ECHO_PIN = 23

    REAR_SENSOR_TRIG_PIN = 14
    REAR_SENSOR_ECHO_PIN = 15

    LEFT_SENSOR_TRIG_PIN = 25
    LEFT_SENSOR_ECHO_PIN = 8

    RIGHT_SENSOR_TRIG_PIN = 7
    RIGHT_SENSOR_ECHO_PIN = 12

    # Values in CM
    MIN_FRONT_DISTANCE = 12
    MIN_BACK_DISTANCE = 16
    MIN_LEFT_DISTANCE = 16
    MIN_RIGHT_DISTANCE = 16
    SIDE_SENSOR_OFFSET = 0
